### ISSUE TITLE
Não consigo executar

### ISSUE THREAD

**Issue by lukasrmattos** [guilhermelhr/unityro#1]
Boa noite Guilherme, estou tentando testar esse seu projeto.

Eu criei o arquivo para habilitar o "Unsafe Code", ao executar a cena, a CPU vai para 100% e nada acontece (já configurei o caminho da minha grf)

Estou utilizando a última versão do Unity.

Esse projeto está funcionando na última versão? Precisa de alguma configuração extra que eu deveria saber?

Desde já, obrigado.

**Comment by guilhermelhr** [comment]
Boa noite, Rodrigo. Os arquivos foram gerados com a versão `2018.3.0f2`.
Sobre a última versão da Unity, não se te dizer mas vou testar aqui logo mais.

**Comment by guilhermelhr** [comment]
Boa noite, Lukas. Os arquivos foram gerados com a versão `2018.3.0f2`.
Sobre a última versão da Unity, não se te dizer mas vou testar aqui logo mais.

**Comment by guilhermelhr** [comment]
Você está tendo problemas com o projeto na Unity ou com o executável compilado?

**Comment by guilhermelhr** [comment]
Consegui rodar com a versão `2019.3.7f1`, segue o passo a passo:

1. Criar um novo projeto.
2. Importar o _unityro-0.1.0.unitypackage_ arrastando ele para os assets.
3. Habilitar o _"Unsafe Code"_ nas opções do _player_.
4. Mudar no arquivo _config_ a localização da _GRF_.
5. Abrir a cena _release_.
6. Play.

Se continuar com problemas, tente [outra GRF](https://ratemyserver.net/index.php?page=download_kROLinks), sugiro uma do kRO.

**Comment by lukasrmattos** [comment]
Quando seleciono o mapa, nada acontece e o unity para de responder

![image](https://user-images.githubusercontent.com/28408973/78041032-9ef54300-7346-11ea-97d3-e8d47502b8f9.png)

Fica para sempre carregando. Vou baixar a data do kro e tentar com a mesma, estou utilizando a do bro.

**Comment by guilhermelhr** [comment]
> Fica para sempre carregando. Vou baixar a data do kro e tentar com a mesma, estou utilizando a do bro.

Conseguiu testar com a GRF do kRO?

**Comment by Danil0v3s** [comment]
Hey, testei com a GRF do kRO e continua a congelar a Unity.
Fiz um debug e o código vai até o `MapLoader.LoadModels` e trava a execução depois do `FileManager.EndBatch`. A princípio achei que fosse devido a ser feito em modo síncrono mas fui olhar e me parece que está tudo em threads. Daí já não sei... Não há exceptions e tanto a Unity quanto o Client Standalone desistem quando se seleciona um mapa maior... 

Tentei com mapas menores e ele carrega ok

Edit: Testei não carregar modelos e tudo faz load. Dentro do `FileManager.EndBatch` quando chamas o `doneEvent.WaitOne()` é que está exatamente pendurando

**Comment by guilhermelhr** [comment]
Oi @daniloleemes. Veja se a memória RAM não está sendo esgotada ao carregar esses mapas maiores.

**Comment by Danil0v3s** [comment]
Oi, não.. A Unity tá a usar apenas 1gb de RAM

![image](https://user-images.githubusercontent.com/13068064/95667781-9a65de80-0b62-11eb-998a-097bd518e7c7.png)

**Comment by guilhermelhr** [comment]
Entendi. Seria necessário debugar mais mas no momento eu estou sem tempo para mexer nesse projeto. Você parece estar no caminho certo. Se conseguir resolver eu agradeceria um pr.

**Comment by Danil0v3s** [comment]
Ainda to tentando entender mais o projeto... Assim que eu conseguir alguma coisa eu faço um PR, mas acredito que a saída aqui é paralelizar mais um bocado. Entretanto se tiver alguma direção, diz q eu tento seguir com ela
