### ISSUE TITLE
Unable to find Config.txt

### ISSUE THREAD

**Issue by ghost** [guilhermelhr/unityro#2]
Hi,
I can't find config.txt, which folder should be in to and what is it supposed to be inside exactly?

Thanks

**Comment by guilhermelhr** [comment]
If you've downloaded the standalone executable ([unityro-0.1.0.zip](https://github.com/guilhermelhr/unityro/releases/download/0.1.0/unityro-0.1.0.zip)), it is located at the _unityro_Data_ directory.
If you've downloaded the Unity package ([unityro-0.1.0.unitypackage](https://github.com/guilhermelhr/unityro/releases/download/0.1.0/unityro-0.1.0.unitypackage)), it will be on the Assets folder after you import it into Unity.

For the content, just change the example that will be in it to the location of a _data.grf_  you obtained somewhere else.

**Comment by ghost** [comment]
Amazing, thank you.
