### ISSUE TITLE
How to compile this project

### ISSUE THREAD

**Issue by CairoLee** [guilhermelhr/unityro#20]
Wow, this is a huge project... I am super look forward it!

I don't have any experience with unity, so how should I compile this project?
No need to describe in detail, I need some keyword like IDE name as a guide, I look forward to receiving a reply

**Comment by guilhermelhr** [comment]
Hello. You just need [Unity](https://unity.com), it will install Visual Studio for you.
After installing it, you can clone this project and import it there.

**Comment by CairoLee** [comment]
Thank you for your response. According to your guide

1. Downloaded Unity for personal
2. Install Unity Hub and Sign up my Unity ID
3. Update unity hub to the latest version
4. Clone our project
5. Import project into Unity Hub
6. Install Engine Version to 2020.1.7f1c1
7. Click the Project and open the Unity Editor
8. Set `{project}\Assets\config.txt` to my `data.grf` file path

Now, I can see the UnityRO in the Project Windows.
But when i click the run button or use Ctrl + B to build the project, the result is not as expected. 

Did I miss any operation?

![image](https://user-images.githubusercontent.com/4458917/102162932-15ca7000-3ec5-11eb-93a7-a3fde3d8a892.png)

**Comment by guilhermelhr** [comment]
In Unity, on the project navigator at the bottom, open the **ragnarok** or **release** scene inside the Scenes directory. Then click on the run button.

**Comment by CairoLee** [comment]
Bump up... I can see the map now.

![image](https://user-images.githubusercontent.com/4458917/102166480-267be580-3ec7-11eb-957c-700611898572.png)

After build, i set up the config.txt in unityro_Data, now it's work fine.

![image](https://user-images.githubusercontent.com/4458917/102179275-d4948900-3ee1-11eb-9667-84bf2b322737.png)

Thank you for your patience and guidance. I am very looking forward to this project... Ragnarok Online has many mature server-side simulators, but there have been few in-depth studies on the client side. It can perfectly improve this situation.

**Comment by guilhermelhr** [comment]
No problem! Thank you. You can join us on Discord if you want to get more frequent updates. Link is on the README.
