### ISSUE TITLE
Figure out whether it's worth to use structs and marshalling to represent packets

### ISSUE THREAD

**Issue by Danil0v3s** [guilhermelhr/unityro#37]
At this moment we deal with the byte array in such a way where we must manually read each field from the a BinaryReader created from that array.

Goal would be to have structs (ideally the same as rA/herc) and to use De/Marshalling to translate those into/from byte awways.

Pros:
- No need to manually read/write each field

Cons:
- C# doesn't deal with structs padding/packing in the same way C/C++ does. We might run into serious trouble.

Does anyone have any input on this?

**Comment by Danil0v3s** [comment]
https://stackoverflow.com/questions/2871/reading-a-c-c-data-structure-in-c-sharp-from-a-byte-array

**Comment by Danil0v3s** [comment]
Another option would be write a native c++ lib so we can be literally paired with servers

**Comment by LiamKarlMitchell** [comment]
https://www.genericgamedev.com/general/converting-between-structs-and-byte-arrays/
Interesting to see how you do it.
I'de go manual binary reader/writer subclassed but its more effort.
Would try to have instances of structs an an observer method to execute for each.
Could automate a bunch of it but for handling bits...

The padding if you marshal can be specified by the way.

**Comment by Danil0v3s** [comment]
Marshal seem to be the most effective in terms of reusing and ease. The padding however is my only concern, from what I understood from Microsoft's docs, you have to specify a pack attribute for your structs but that size may vary depending on our structure.

I like the idea of creating a C++ library because if would remove all that networking code from inside the game's code and personally I think such separation of concerns is beautiful

**Comment by LiamKarlMitchell** [comment]
That would be neat yeah how would you get the structures over into managed .net?
Would need to marshal the struct from C++ to C# then call a function?

**Comment by Danil0v3s** [comment]
Took some time to dig on this and happens that we cannot use the way I intended. My intention was to somehow export the rA structs from C++ and whenever we receive packets from server, call a C++ function with our byte array so C++ can cast it to a struct provided...

Closing as won't do
