### ISSUE TITLE
ROCamera.cs - How does it work?

### ISSUE THREAD

**Issue by Danil0v3s** [guilhermelhr/unityro#4]
So, hey. I've been wandering around the code and couldn't find any example of the ROCamera being used anywhere. 

Is that class working? How's it supposed to be used? As a Camera Component or as the Camera itself?

I could notice the `//GL` at the end of `Update()`. Does that stands for `Good Luck`? haha

**Comment by guilhermelhr** [comment]
> Is that class working?

Not really. IIRC I just ported it from roBrowser but never got around to actually using it. I don't think it is functional.

> I could notice the //GL at the end of Update(). Does that stands for Good Luck? haha

LOL it must be that there was some opengl there in roBrowser that I did not bother porting over.
