### ISSUE TITLE
Create "build time" tool/script to extract GRFs and make it possible to run WebGL builds

### ISSUE THREAD

**Issue by Danil0v3s** [guilhermelhr/unityro#56]
**Description**
It seems to me that WebGL builds pack everything into its bundle not allowing us to change the `config.json` like we use to do in the standalone build. 

We've discussed some time ago that it would be nice to have a script/tool/whatever sense to run before a build or at the first time someone downloads the project that would extract the GRFs and build the prefabs of cities, items, mobs and save them somewhere  Unity can easily access in any kind of build

**Comment by zhad3** [comment]
Hey, while I cannot help with the script itself I can blatantly advertise my CLI tool to extract GRFs https://github.com/zhad3/zextractor ;)
Maybe it can be of help.

**Comment by Danil0v3s** [comment]
Hi! 

We've ended up just extending what we already had and built a Editor tool which extracts the files to inside Resources.

Anyways, thank you for willing to help!
